[%- MACRO convertType(type)
    SWITCH type -%]
    [%- CASE 'Boolean' -%]bool
    [%- CASE 'Integer' -%]qint32
    [%- CASE 'Real' -%]qreal
    [%- CASE 'UnlimitedNatural' -%]qint32
    [%- CASE -%]
        [%- IF !type.remove('^' _ currentPackage _ '::').search('::') -%]
            [%- 'Q' _ type.remove('^' _ currentPackage _ '::') -%]
        [%- ELSE -%]
            [%- FOREACH classifier IN type.split('::') -%]
                [%- IF !loop.first -%]
                    [%- '::' -%]
                [%- END -%]
                [%- IF loop.last -%]
                    [%- 'Q' -%]
                [%- END -%]
                [%- classifier -%]
            [%- END -%]
        [%- END -%]
    [%- END -%]
[%- MACRO handleModifiers(property, const, pointer, collection) BLOCK -%]
    [%- IF property.type.href.defined -%]
        [%- type = property.type.href -%]
    [%- ELSIF property.type.defined -%]
        [%- type = property.type -%]
    [%- ELSE -%]
        [%- type = property -%]
    [%- END -%]
    [%- convertedType = convertType(type.split('#').last.replace('-', '::')) -%]
    [%- IF (property.upperValue.value != '*' || property.isReadOnly) && const && convertedType.substr(0, 1) == 'Q' && !convertedType.search('Kind') -%]
        [%- 'const ' -%]
    [%- END -%]
    [%- IF property.upperValue.value == '*' && collection -%]
        [%- 'QList<' -%]
    [%- END -%]
    [%- convertedType -%]
    [%- IF collection -%][%- ' ' -%][%- END -%]
    [%- IF property.upperValue.value == '*' && collection -%]
        [%- '*> ' -%]
    [%- END -%]
    [%- IF pointer && convertedType.substr(0, 1) == 'Q' && !convertedType.search('Kind') -%]
        [%- '*' -%]
    [%- END -%]
[%- END -%]
[%- MACRO unqualifiedType(property, const, pointer, collection)
    IF property.type.defined -%]
        [%- handleModifiers(property, const, pointer, collection) -%]
    [%- ELSE -%]
        [%- convertType(property.split('#').last.replace('-', '::')) -%]
[%- END -%]
[%- MACRO GENERATEPROPERTIES(association)
    FOREACH property IN classData.ownedAttribute -%]
        [%- IF (property.value.association.defined && association) || (!property.value.association.defined && !association) %]
    Q_PROPERTY([%- IF property.value.isReadOnly -%]const [%- END -%]${unqualifiedType(property.value, 0, 1, 1)} ${property.key} READ ${property.key}
            [%- IF property.value.isReadOnly != 'true' && property.value.upperValue.value != '*' %]
                [%- ' WRITE set' -%]
                [%- IF property.key.substr(0, 2) == 'is' -%]
                    [%- property.key.substr(2).ucfirst -%]
                [%- ELSE -%]
                    [%- property.key.ucfirst -%]
                [%- END- %]
            [%- END -%]
            [%- ')' -%]
        [%- END -%]
    [%- END -%]
[%- MACRO GENERATEACCESSORS(association, declaration)
    FOREACH property IN classData.ownedAttribute -%]
        [%- IF ((property.value.association.defined && association) || (!property.value.association.defined && !association))
                && !(property.value.isDerived && !property.value.isDerivedUnion) %]
[% IF declaration %]    [% END %]${unqualifiedType(property.value, 1, 1, 1)}[%- IF !declaration -%]Q${className}::[%- END -%]${property.key}()
            [%- IF property.value.isReadOnly && const -%]
                [%- 'const ' -%]
            [%- END -%]
            [%- IF declaration -%]
                [%- ';' -%]
            [%- ELSE %]
{
}

            [%- END -%]
            [%- IF property.value.isReadOnly != 'true' && property.value.upperValue.value != '*' %]
[% IF declaration %]    [% END %]void [%- IF !declaration -%]Q${className}::[%- END -%]set
            [%- IF property.key.substr(0, 2) == 'is' -%]
                [%- property.key.substr(2).ucfirst -%]
            [%- ELSE -%]
                [%- property.key.ucfirst -%]
            [%- END- %]
            [%- '(' _ unqualifiedType(property.value, 1, 1, 1) -%]
            [%- IF property.key.substr(0, 2) == 'is' -%]
                [%- property.key.substr(2).lcfirst -%]
            [%- ELSE -%]
                [%- property.key -%]
            [%- END- %]
            [%- ')' -%]
            [%- IF declaration -%]
                [%- ';' -%]
            [%- ELSE %]
{
}

            [%- END -%]
        [%- END -%]
    [%- END -%]
[%- END %]
[%- MACRO GENERATEOPERATIONS(declaration) BLOCK -%]
    [%- FOREACH operation IN classData.ownedOperation -%]
        [%- return = void -%]
        [%- FOREACH parameter IN operation.value.ownedParameter -%]
            [%- IF parameter.value.direction == 'return' -%]
                [%- return = unqualifiedType(parameter.value, 1, 1, 1) -%]
            [%- END -%]
        [%- END %]
[% IF declaration %]    [% END %]${return}[%- IF !declaration -%]Q${className}::[%- END -%]${operation.key}(
        [%- returnDelta = 1 -%]
        [%- FOREACH parameter IN operation.value.ownedParameter -%]
            [%- IF parameter.value.direction != 'return' -%]
                [%- unqualifiedType(parameter.value, 1, 1, 1) _ parameter.key -%]
                [%- IF loop.count < loop.size - returnDelta -%]
                    [%- ', ' -%]
                [%- END -%]
            [%- ELSE -%]
                [%- returnDelta = 0 -%]
            [%- END -%]
        [%- END -%]
        [%- ')' -%]
        [%- IF operation.value.isQuery -%]
            [%- ' const' -%]
        [%- END -%]
        [%- IF declaration -%]
            [%- ';' -%]
        [%- ELSE %]
{
}

        [%- END -%]
    [%- END %]
[%- END -%]
[%- MACRO GENERATEINCLUDES BLOCK -%]
    [%- FOREACH property IN classData.ownedAttribute -%]
        [%- convertedType = unqualifiedType(property.value, 0, 0, 0) -%]
        [%- IF convertedType.substr(0, 1) == 'Q' && convertedType.search('Kind') %]
#include <QtUml/QtEnumeration>
        [%- END -%]
    [%- END -%]
    [%- FOREACH property IN classData.ownedAttribute -%]
        [%- convertedType = unqualifiedType(property.value, 0, 0, 0) -%]
        [%- IF convertedType.substr(0, 1) == 'Q' && !convertedType.search('Kind') %]
class ${convertedType};
        [%- END -%]
    [%- END -%]
[%- END -%]
