/****************************************************************************
**
** Copyright (C) 2012 Sandro S. Andrade <sandroandrade@kde.org>
** Contact: http://www.qt-project.org/
**
** This file is part of the QtUml module of the Qt Toolkit.
**
** $QT_BEGIN_LICENSE:LGPL$
** GNU Lesser General Public License Usage
** This file may be used under the terms of the GNU Lesser General Public
** License version 2.1 as published by the Free Software Foundation and
** appearing in the file LICENSE.LGPL included in the packaging of this
** file. Please review the following information to ensure the GNU Lesser
** General Public License version 2.1 requirements will be met:
** http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
** In addition, as a special exception, Nokia gives you certain additional
** rights. These rights are described in the Nokia Qt LGPL Exception
** version 1.1, included in the file LGPL_EXCEPTION.txt in this package.
**
** GNU General Public License Usage
** Alternatively, this file may be used under the terms of the GNU General
** Public License version 3.0 as published by the Free Software Foundation
** and appearing in the file LICENSE.GPL included in the packaging of this
** file. Please review the following information to ensure the GNU General
** Public License version 3.0 requirements will be met:
** http://www.gnu.org/copyleft/gpl.html.
**
** Other Usage
** Alternatively, this file may be used in accordance with the terms and
** conditions contained in a signed written agreement between you and Nokia.
**
**
**
**
**
**
** $QT_END_LICENSE$
**
****************************************************************************/

#include "qumlmetamodel.h"

QT_BEGIN_NAMESPACE_QTUML

void QUmlMetaModel::init(QScriptEngine *scriptEngine)
{
    qRegisterMetaType<QAbstraction *>();
    qRegisterMetaType<QList<QAbstraction *>>();
    qRegisterMetaType<QSet<QAbstraction *>>();
    qRegisterMetaType<QAcceptCallAction *>();
    qRegisterMetaType<QList<QAcceptCallAction *>>();
    qRegisterMetaType<QSet<QAcceptCallAction *>>();
    qRegisterMetaType<QAcceptEventAction *>();
    qRegisterMetaType<QList<QAcceptEventAction *>>();
    qRegisterMetaType<QSet<QAcceptEventAction *>>();
    qRegisterMetaType<QAction *>();
    qRegisterMetaType<QList<QAction *>>();
    qRegisterMetaType<QSet<QAction *>>();
    qRegisterMetaType<QActionExecutionSpecification *>();
    qRegisterMetaType<QList<QActionExecutionSpecification *>>();
    qRegisterMetaType<QSet<QActionExecutionSpecification *>>();
    qRegisterMetaType<QActionInputPin *>();
    qRegisterMetaType<QList<QActionInputPin *>>();
    qRegisterMetaType<QSet<QActionInputPin *>>();
    qRegisterMetaType<QActivity *>();
    qRegisterMetaType<QList<QActivity *>>();
    qRegisterMetaType<QSet<QActivity *>>();
    qRegisterMetaType<QActivityEdge *>();
    qRegisterMetaType<QList<QActivityEdge *>>();
    qRegisterMetaType<QSet<QActivityEdge *>>();
    qRegisterMetaType<QActivityFinalNode *>();
    qRegisterMetaType<QList<QActivityFinalNode *>>();
    qRegisterMetaType<QSet<QActivityFinalNode *>>();
    qRegisterMetaType<QActivityGroup *>();
    qRegisterMetaType<QList<QActivityGroup *>>();
    qRegisterMetaType<QSet<QActivityGroup *>>();
    qRegisterMetaType<QActivityNode *>();
    qRegisterMetaType<QList<QActivityNode *>>();
    qRegisterMetaType<QSet<QActivityNode *>>();
    qRegisterMetaType<QActivityParameterNode *>();
    qRegisterMetaType<QList<QActivityParameterNode *>>();
    qRegisterMetaType<QSet<QActivityParameterNode *>>();
    qRegisterMetaType<QActivityPartition *>();
    qRegisterMetaType<QList<QActivityPartition *>>();
    qRegisterMetaType<QSet<QActivityPartition *>>();
    qRegisterMetaType<QActor *>();
    qRegisterMetaType<QList<QActor *>>();
    qRegisterMetaType<QSet<QActor *>>();
    qRegisterMetaType<QAddStructuralFeatureValueAction *>();
    qRegisterMetaType<QList<QAddStructuralFeatureValueAction *>>();
    qRegisterMetaType<QSet<QAddStructuralFeatureValueAction *>>();
    qRegisterMetaType<QAddVariableValueAction *>();
    qRegisterMetaType<QList<QAddVariableValueAction *>>();
    qRegisterMetaType<QSet<QAddVariableValueAction *>>();
    qRegisterMetaType<QAnyReceiveEvent *>();
    qRegisterMetaType<QList<QAnyReceiveEvent *>>();
    qRegisterMetaType<QSet<QAnyReceiveEvent *>>();
    qRegisterMetaType<QArtifact *>();
    qRegisterMetaType<QList<QArtifact *>>();
    qRegisterMetaType<QSet<QArtifact *>>();
    qRegisterMetaType<QAssociation *>();
    qRegisterMetaType<QList<QAssociation *>>();
    qRegisterMetaType<QSet<QAssociation *>>();
    qRegisterMetaType<QAssociationClass *>();
    qRegisterMetaType<QList<QAssociationClass *>>();
    qRegisterMetaType<QSet<QAssociationClass *>>();
    qRegisterMetaType<QBehavior *>();
    qRegisterMetaType<QList<QBehavior *>>();
    qRegisterMetaType<QSet<QBehavior *>>();
    qRegisterMetaType<QBehaviorExecutionSpecification *>();
    qRegisterMetaType<QList<QBehaviorExecutionSpecification *>>();
    qRegisterMetaType<QSet<QBehaviorExecutionSpecification *>>();
    qRegisterMetaType<QBehavioralFeature *>();
    qRegisterMetaType<QList<QBehavioralFeature *>>();
    qRegisterMetaType<QSet<QBehavioralFeature *>>();
    qRegisterMetaType<QBehavioredClassifier *>();
    qRegisterMetaType<QList<QBehavioredClassifier *>>();
    qRegisterMetaType<QSet<QBehavioredClassifier *>>();
    qRegisterMetaType<QBroadcastSignalAction *>();
    qRegisterMetaType<QList<QBroadcastSignalAction *>>();
    qRegisterMetaType<QSet<QBroadcastSignalAction *>>();
    qRegisterMetaType<QCallAction *>();
    qRegisterMetaType<QList<QCallAction *>>();
    qRegisterMetaType<QSet<QCallAction *>>();
    qRegisterMetaType<QCallBehaviorAction *>();
    qRegisterMetaType<QList<QCallBehaviorAction *>>();
    qRegisterMetaType<QSet<QCallBehaviorAction *>>();
    qRegisterMetaType<QCallEvent *>();
    qRegisterMetaType<QList<QCallEvent *>>();
    qRegisterMetaType<QSet<QCallEvent *>>();
    qRegisterMetaType<QCallOperationAction *>();
    qRegisterMetaType<QList<QCallOperationAction *>>();
    qRegisterMetaType<QSet<QCallOperationAction *>>();
    qRegisterMetaType<QCentralBufferNode *>();
    qRegisterMetaType<QList<QCentralBufferNode *>>();
    qRegisterMetaType<QSet<QCentralBufferNode *>>();
    qRegisterMetaType<QChangeEvent *>();
    qRegisterMetaType<QList<QChangeEvent *>>();
    qRegisterMetaType<QSet<QChangeEvent *>>();
    qRegisterMetaType<QClass *>();
    qRegisterMetaType<QList<QClass *>>();
    qRegisterMetaType<QSet<QClass *>>();
    qRegisterMetaType<QClassifier *>();
    qRegisterMetaType<QList<QClassifier *>>();
    qRegisterMetaType<QSet<QClassifier *>>();
    qRegisterMetaType<QClassifierTemplateParameter *>();
    qRegisterMetaType<QList<QClassifierTemplateParameter *>>();
    qRegisterMetaType<QSet<QClassifierTemplateParameter *>>();
    qRegisterMetaType<QClause *>();
    qRegisterMetaType<QList<QClause *>>();
    qRegisterMetaType<QSet<QClause *>>();
    qRegisterMetaType<QClearAssociationAction *>();
    qRegisterMetaType<QList<QClearAssociationAction *>>();
    qRegisterMetaType<QSet<QClearAssociationAction *>>();
    qRegisterMetaType<QClearStructuralFeatureAction *>();
    qRegisterMetaType<QList<QClearStructuralFeatureAction *>>();
    qRegisterMetaType<QSet<QClearStructuralFeatureAction *>>();
    qRegisterMetaType<QClearVariableAction *>();
    qRegisterMetaType<QList<QClearVariableAction *>>();
    qRegisterMetaType<QSet<QClearVariableAction *>>();
    qRegisterMetaType<QCollaboration *>();
    qRegisterMetaType<QList<QCollaboration *>>();
    qRegisterMetaType<QSet<QCollaboration *>>();
    qRegisterMetaType<QCollaborationUse *>();
    qRegisterMetaType<QList<QCollaborationUse *>>();
    qRegisterMetaType<QSet<QCollaborationUse *>>();
    qRegisterMetaType<QCombinedFragment *>();
    qRegisterMetaType<QList<QCombinedFragment *>>();
    qRegisterMetaType<QSet<QCombinedFragment *>>();
    qRegisterMetaType<QComment *>();
    qRegisterMetaType<QList<QComment *>>();
    qRegisterMetaType<QSet<QComment *>>();
    qRegisterMetaType<QCommunicationPath *>();
    qRegisterMetaType<QList<QCommunicationPath *>>();
    qRegisterMetaType<QSet<QCommunicationPath *>>();
    qRegisterMetaType<QComponent *>();
    qRegisterMetaType<QList<QComponent *>>();
    qRegisterMetaType<QSet<QComponent *>>();
    qRegisterMetaType<QComponentRealization *>();
    qRegisterMetaType<QList<QComponentRealization *>>();
    qRegisterMetaType<QSet<QComponentRealization *>>();
    qRegisterMetaType<QConditionalNode *>();
    qRegisterMetaType<QList<QConditionalNode *>>();
    qRegisterMetaType<QSet<QConditionalNode *>>();
    qRegisterMetaType<QConnectableElement *>();
    qRegisterMetaType<QList<QConnectableElement *>>();
    qRegisterMetaType<QSet<QConnectableElement *>>();
    qRegisterMetaType<QConnectableElementTemplateParameter *>();
    qRegisterMetaType<QList<QConnectableElementTemplateParameter *>>();
    qRegisterMetaType<QSet<QConnectableElementTemplateParameter *>>();
    qRegisterMetaType<QConnectionPointReference *>();
    qRegisterMetaType<QList<QConnectionPointReference *>>();
    qRegisterMetaType<QSet<QConnectionPointReference *>>();
    qRegisterMetaType<QConnector *>();
    qRegisterMetaType<QList<QConnector *>>();
    qRegisterMetaType<QSet<QConnector *>>();
    qRegisterMetaType<QConnectorEnd *>();
    qRegisterMetaType<QList<QConnectorEnd *>>();
    qRegisterMetaType<QSet<QConnectorEnd *>>();
    qRegisterMetaType<QConsiderIgnoreFragment *>();
    qRegisterMetaType<QList<QConsiderIgnoreFragment *>>();
    qRegisterMetaType<QSet<QConsiderIgnoreFragment *>>();
    qRegisterMetaType<QConstraint *>();
    qRegisterMetaType<QList<QConstraint *>>();
    qRegisterMetaType<QSet<QConstraint *>>();
    qRegisterMetaType<QContinuation *>();
    qRegisterMetaType<QList<QContinuation *>>();
    qRegisterMetaType<QSet<QContinuation *>>();
    qRegisterMetaType<QControlFlow *>();
    qRegisterMetaType<QList<QControlFlow *>>();
    qRegisterMetaType<QSet<QControlFlow *>>();
    qRegisterMetaType<QControlNode *>();
    qRegisterMetaType<QList<QControlNode *>>();
    qRegisterMetaType<QSet<QControlNode *>>();
    qRegisterMetaType<QCreateLinkAction *>();
    qRegisterMetaType<QList<QCreateLinkAction *>>();
    qRegisterMetaType<QSet<QCreateLinkAction *>>();
    qRegisterMetaType<QCreateLinkObjectAction *>();
    qRegisterMetaType<QList<QCreateLinkObjectAction *>>();
    qRegisterMetaType<QSet<QCreateLinkObjectAction *>>();
    qRegisterMetaType<QCreateObjectAction *>();
    qRegisterMetaType<QList<QCreateObjectAction *>>();
    qRegisterMetaType<QSet<QCreateObjectAction *>>();
    qRegisterMetaType<QDataStoreNode *>();
    qRegisterMetaType<QList<QDataStoreNode *>>();
    qRegisterMetaType<QSet<QDataStoreNode *>>();
    qRegisterMetaType<QDataType *>();
    qRegisterMetaType<QList<QDataType *>>();
    qRegisterMetaType<QSet<QDataType *>>();
    qRegisterMetaType<QDecisionNode *>();
    qRegisterMetaType<QList<QDecisionNode *>>();
    qRegisterMetaType<QSet<QDecisionNode *>>();
    qRegisterMetaType<QDependency *>();
    qRegisterMetaType<QList<QDependency *>>();
    qRegisterMetaType<QSet<QDependency *>>();
    qRegisterMetaType<QDeployedArtifact *>();
    qRegisterMetaType<QList<QDeployedArtifact *>>();
    qRegisterMetaType<QSet<QDeployedArtifact *>>();
    qRegisterMetaType<QDeployment *>();
    qRegisterMetaType<QList<QDeployment *>>();
    qRegisterMetaType<QSet<QDeployment *>>();
    qRegisterMetaType<QDeploymentSpecification *>();
    qRegisterMetaType<QList<QDeploymentSpecification *>>();
    qRegisterMetaType<QSet<QDeploymentSpecification *>>();
    qRegisterMetaType<QDeploymentTarget *>();
    qRegisterMetaType<QList<QDeploymentTarget *>>();
    qRegisterMetaType<QSet<QDeploymentTarget *>>();
    qRegisterMetaType<QDestroyLinkAction *>();
    qRegisterMetaType<QList<QDestroyLinkAction *>>();
    qRegisterMetaType<QSet<QDestroyLinkAction *>>();
    qRegisterMetaType<QDestroyObjectAction *>();
    qRegisterMetaType<QList<QDestroyObjectAction *>>();
    qRegisterMetaType<QSet<QDestroyObjectAction *>>();
    qRegisterMetaType<QDestructionOccurrenceSpecification *>();
    qRegisterMetaType<QList<QDestructionOccurrenceSpecification *>>();
    qRegisterMetaType<QSet<QDestructionOccurrenceSpecification *>>();
    qRegisterMetaType<QDevice *>();
    qRegisterMetaType<QList<QDevice *>>();
    qRegisterMetaType<QSet<QDevice *>>();
    qRegisterMetaType<QDirectedRelationship *>();
    qRegisterMetaType<QList<QDirectedRelationship *>>();
    qRegisterMetaType<QSet<QDirectedRelationship *>>();
    qRegisterMetaType<QDuration *>();
    qRegisterMetaType<QList<QDuration *>>();
    qRegisterMetaType<QSet<QDuration *>>();
    qRegisterMetaType<QDurationConstraint *>();
    qRegisterMetaType<QList<QDurationConstraint *>>();
    qRegisterMetaType<QSet<QDurationConstraint *>>();
    qRegisterMetaType<QDurationInterval *>();
    qRegisterMetaType<QList<QDurationInterval *>>();
    qRegisterMetaType<QSet<QDurationInterval *>>();
    qRegisterMetaType<QDurationObservation *>();
    qRegisterMetaType<QList<QDurationObservation *>>();
    qRegisterMetaType<QSet<QDurationObservation *>>();
    qRegisterMetaType<QElement *>();
    qRegisterMetaType<QList<QElement *>>();
    qRegisterMetaType<QSet<QElement *>>();
    qRegisterMetaType<QElementImport *>();
    qRegisterMetaType<QList<QElementImport *>>();
    qRegisterMetaType<QSet<QElementImport *>>();
    qRegisterMetaType<QEncapsulatedClassifier *>();
    qRegisterMetaType<QList<QEncapsulatedClassifier *>>();
    qRegisterMetaType<QSet<QEncapsulatedClassifier *>>();
    qRegisterMetaType<QEnumeration *>();
    qRegisterMetaType<QList<QEnumeration *>>();
    qRegisterMetaType<QSet<QEnumeration *>>();
    qRegisterMetaType<QEnumerationLiteral *>();
    qRegisterMetaType<QList<QEnumerationLiteral *>>();
    qRegisterMetaType<QSet<QEnumerationLiteral *>>();
    qRegisterMetaType<QEvent *>();
    qRegisterMetaType<QList<QEvent *>>();
    qRegisterMetaType<QSet<QEvent *>>();
    qRegisterMetaType<QExceptionHandler *>();
    qRegisterMetaType<QList<QExceptionHandler *>>();
    qRegisterMetaType<QSet<QExceptionHandler *>>();
    qRegisterMetaType<QExecutableNode *>();
    qRegisterMetaType<QList<QExecutableNode *>>();
    qRegisterMetaType<QSet<QExecutableNode *>>();
    qRegisterMetaType<QExecutionEnvironment *>();
    qRegisterMetaType<QList<QExecutionEnvironment *>>();
    qRegisterMetaType<QSet<QExecutionEnvironment *>>();
    qRegisterMetaType<QExecutionOccurrenceSpecification *>();
    qRegisterMetaType<QList<QExecutionOccurrenceSpecification *>>();
    qRegisterMetaType<QSet<QExecutionOccurrenceSpecification *>>();
    qRegisterMetaType<QExecutionSpecification *>();
    qRegisterMetaType<QList<QExecutionSpecification *>>();
    qRegisterMetaType<QSet<QExecutionSpecification *>>();
    qRegisterMetaType<QExpansionNode *>();
    qRegisterMetaType<QList<QExpansionNode *>>();
    qRegisterMetaType<QSet<QExpansionNode *>>();
    qRegisterMetaType<QExpansionRegion *>();
    qRegisterMetaType<QList<QExpansionRegion *>>();
    qRegisterMetaType<QSet<QExpansionRegion *>>();
    qRegisterMetaType<QExpression *>();
    qRegisterMetaType<QList<QExpression *>>();
    qRegisterMetaType<QSet<QExpression *>>();
    qRegisterMetaType<QExtend *>();
    qRegisterMetaType<QList<QExtend *>>();
    qRegisterMetaType<QSet<QExtend *>>();
    qRegisterMetaType<QExtension *>();
    qRegisterMetaType<QList<QExtension *>>();
    qRegisterMetaType<QSet<QExtension *>>();
    qRegisterMetaType<QExtensionEnd *>();
    qRegisterMetaType<QList<QExtensionEnd *>>();
    qRegisterMetaType<QSet<QExtensionEnd *>>();
    qRegisterMetaType<QExtensionPoint *>();
    qRegisterMetaType<QList<QExtensionPoint *>>();
    qRegisterMetaType<QSet<QExtensionPoint *>>();
    qRegisterMetaType<QFeature *>();
    qRegisterMetaType<QList<QFeature *>>();
    qRegisterMetaType<QSet<QFeature *>>();
    qRegisterMetaType<QFinalNode *>();
    qRegisterMetaType<QList<QFinalNode *>>();
    qRegisterMetaType<QSet<QFinalNode *>>();
    qRegisterMetaType<QFinalState *>();
    qRegisterMetaType<QList<QFinalState *>>();
    qRegisterMetaType<QSet<QFinalState *>>();
    qRegisterMetaType<QFlowFinalNode *>();
    qRegisterMetaType<QList<QFlowFinalNode *>>();
    qRegisterMetaType<QSet<QFlowFinalNode *>>();
    qRegisterMetaType<QForkNode *>();
    qRegisterMetaType<QList<QForkNode *>>();
    qRegisterMetaType<QSet<QForkNode *>>();
    qRegisterMetaType<QFunctionBehavior *>();
    qRegisterMetaType<QList<QFunctionBehavior *>>();
    qRegisterMetaType<QSet<QFunctionBehavior *>>();
    qRegisterMetaType<QGate *>();
    qRegisterMetaType<QList<QGate *>>();
    qRegisterMetaType<QSet<QGate *>>();
    qRegisterMetaType<QGeneralOrdering *>();
    qRegisterMetaType<QList<QGeneralOrdering *>>();
    qRegisterMetaType<QSet<QGeneralOrdering *>>();
    qRegisterMetaType<QGeneralization *>();
    qRegisterMetaType<QList<QGeneralization *>>();
    qRegisterMetaType<QSet<QGeneralization *>>();
    qRegisterMetaType<QGeneralizationSet *>();
    qRegisterMetaType<QList<QGeneralizationSet *>>();
    qRegisterMetaType<QSet<QGeneralizationSet *>>();
    qRegisterMetaType<QImage *>();
    qRegisterMetaType<QList<QImage *>>();
    qRegisterMetaType<QSet<QImage *>>();
    qRegisterMetaType<QInclude *>();
    qRegisterMetaType<QList<QInclude *>>();
    qRegisterMetaType<QSet<QInclude *>>();
    qRegisterMetaType<QInformationFlow *>();
    qRegisterMetaType<QList<QInformationFlow *>>();
    qRegisterMetaType<QSet<QInformationFlow *>>();
    qRegisterMetaType<QInformationItem *>();
    qRegisterMetaType<QList<QInformationItem *>>();
    qRegisterMetaType<QSet<QInformationItem *>>();
    qRegisterMetaType<QInitialNode *>();
    qRegisterMetaType<QList<QInitialNode *>>();
    qRegisterMetaType<QSet<QInitialNode *>>();
    qRegisterMetaType<QInputPin *>();
    qRegisterMetaType<QList<QInputPin *>>();
    qRegisterMetaType<QSet<QInputPin *>>();
    qRegisterMetaType<QInstanceSpecification *>();
    qRegisterMetaType<QList<QInstanceSpecification *>>();
    qRegisterMetaType<QSet<QInstanceSpecification *>>();
    qRegisterMetaType<QInstanceValue *>();
    qRegisterMetaType<QList<QInstanceValue *>>();
    qRegisterMetaType<QSet<QInstanceValue *>>();
    qRegisterMetaType<QInteraction *>();
    qRegisterMetaType<QList<QInteraction *>>();
    qRegisterMetaType<QSet<QInteraction *>>();
    qRegisterMetaType<QInteractionConstraint *>();
    qRegisterMetaType<QList<QInteractionConstraint *>>();
    qRegisterMetaType<QSet<QInteractionConstraint *>>();
    qRegisterMetaType<QInteractionFragment *>();
    qRegisterMetaType<QList<QInteractionFragment *>>();
    qRegisterMetaType<QSet<QInteractionFragment *>>();
    qRegisterMetaType<QInteractionOperand *>();
    qRegisterMetaType<QList<QInteractionOperand *>>();
    qRegisterMetaType<QSet<QInteractionOperand *>>();
    qRegisterMetaType<QInteractionUse *>();
    qRegisterMetaType<QList<QInteractionUse *>>();
    qRegisterMetaType<QSet<QInteractionUse *>>();
    qRegisterMetaType<QInterface *>();
    qRegisterMetaType<QList<QInterface *>>();
    qRegisterMetaType<QSet<QInterface *>>();
    qRegisterMetaType<QInterfaceRealization *>();
    qRegisterMetaType<QList<QInterfaceRealization *>>();
    qRegisterMetaType<QSet<QInterfaceRealization *>>();
    qRegisterMetaType<QInterruptibleActivityRegion *>();
    qRegisterMetaType<QList<QInterruptibleActivityRegion *>>();
    qRegisterMetaType<QSet<QInterruptibleActivityRegion *>>();
    qRegisterMetaType<QInterval *>();
    qRegisterMetaType<QList<QInterval *>>();
    qRegisterMetaType<QSet<QInterval *>>();
    qRegisterMetaType<QIntervalConstraint *>();
    qRegisterMetaType<QList<QIntervalConstraint *>>();
    qRegisterMetaType<QSet<QIntervalConstraint *>>();
    qRegisterMetaType<QInvocationAction *>();
    qRegisterMetaType<QList<QInvocationAction *>>();
    qRegisterMetaType<QSet<QInvocationAction *>>();
    qRegisterMetaType<QJoinNode *>();
    qRegisterMetaType<QList<QJoinNode *>>();
    qRegisterMetaType<QSet<QJoinNode *>>();
    qRegisterMetaType<QLifeline *>();
    qRegisterMetaType<QList<QLifeline *>>();
    qRegisterMetaType<QSet<QLifeline *>>();
    qRegisterMetaType<QLinkAction *>();
    qRegisterMetaType<QList<QLinkAction *>>();
    qRegisterMetaType<QSet<QLinkAction *>>();
    qRegisterMetaType<QLinkEndCreationData *>();
    qRegisterMetaType<QList<QLinkEndCreationData *>>();
    qRegisterMetaType<QSet<QLinkEndCreationData *>>();
    qRegisterMetaType<QLinkEndData *>();
    qRegisterMetaType<QList<QLinkEndData *>>();
    qRegisterMetaType<QSet<QLinkEndData *>>();
    qRegisterMetaType<QLinkEndDestructionData *>();
    qRegisterMetaType<QList<QLinkEndDestructionData *>>();
    qRegisterMetaType<QSet<QLinkEndDestructionData *>>();
    qRegisterMetaType<QLiteralBoolean *>();
    qRegisterMetaType<QList<QLiteralBoolean *>>();
    qRegisterMetaType<QSet<QLiteralBoolean *>>();
    qRegisterMetaType<QLiteralInteger *>();
    qRegisterMetaType<QList<QLiteralInteger *>>();
    qRegisterMetaType<QSet<QLiteralInteger *>>();
    qRegisterMetaType<QLiteralNull *>();
    qRegisterMetaType<QList<QLiteralNull *>>();
    qRegisterMetaType<QSet<QLiteralNull *>>();
    qRegisterMetaType<QLiteralReal *>();
    qRegisterMetaType<QList<QLiteralReal *>>();
    qRegisterMetaType<QSet<QLiteralReal *>>();
    qRegisterMetaType<QLiteralSpecification *>();
    qRegisterMetaType<QList<QLiteralSpecification *>>();
    qRegisterMetaType<QSet<QLiteralSpecification *>>();
    qRegisterMetaType<QLiteralString *>();
    qRegisterMetaType<QList<QLiteralString *>>();
    qRegisterMetaType<QSet<QLiteralString *>>();
    qRegisterMetaType<QLiteralUnlimitedNatural *>();
    qRegisterMetaType<QList<QLiteralUnlimitedNatural *>>();
    qRegisterMetaType<QSet<QLiteralUnlimitedNatural *>>();
    qRegisterMetaType<QLoopNode *>();
    qRegisterMetaType<QList<QLoopNode *>>();
    qRegisterMetaType<QSet<QLoopNode *>>();
    qRegisterMetaType<QManifestation *>();
    qRegisterMetaType<QList<QManifestation *>>();
    qRegisterMetaType<QSet<QManifestation *>>();
    qRegisterMetaType<QMergeNode *>();
    qRegisterMetaType<QList<QMergeNode *>>();
    qRegisterMetaType<QSet<QMergeNode *>>();
    qRegisterMetaType<QMessage *>();
    qRegisterMetaType<QList<QMessage *>>();
    qRegisterMetaType<QSet<QMessage *>>();
    qRegisterMetaType<QMessageEnd *>();
    qRegisterMetaType<QList<QMessageEnd *>>();
    qRegisterMetaType<QSet<QMessageEnd *>>();
    qRegisterMetaType<QMessageEvent *>();
    qRegisterMetaType<QList<QMessageEvent *>>();
    qRegisterMetaType<QSet<QMessageEvent *>>();
    qRegisterMetaType<QMessageOccurrenceSpecification *>();
    qRegisterMetaType<QList<QMessageOccurrenceSpecification *>>();
    qRegisterMetaType<QSet<QMessageOccurrenceSpecification *>>();
    qRegisterMetaType<QModel *>();
    qRegisterMetaType<QList<QModel *>>();
    qRegisterMetaType<QSet<QModel *>>();
    qRegisterMetaType<QMultiplicityElement *>();
    qRegisterMetaType<QList<QMultiplicityElement *>>();
    qRegisterMetaType<QSet<QMultiplicityElement *>>();
    qRegisterMetaType<QNamedElement *>();
    qRegisterMetaType<QList<QNamedElement *>>();
    qRegisterMetaType<QSet<QNamedElement *>>();
    qRegisterMetaType<QNamespace *>();
    qRegisterMetaType<QList<QNamespace *>>();
    qRegisterMetaType<QSet<QNamespace *>>();
    qRegisterMetaType<QNode *>();
    qRegisterMetaType<QList<QNode *>>();
    qRegisterMetaType<QSet<QNode *>>();
    qRegisterMetaType<QObjectFlow *>();
    qRegisterMetaType<QList<QObjectFlow *>>();
    qRegisterMetaType<QSet<QObjectFlow *>>();
    qRegisterMetaType<QObjectNode *>();
    qRegisterMetaType<QList<QObjectNode *>>();
    qRegisterMetaType<QSet<QObjectNode *>>();
    qRegisterMetaType<QObservation *>();
    qRegisterMetaType<QList<QObservation *>>();
    qRegisterMetaType<QSet<QObservation *>>();
    qRegisterMetaType<QOccurrenceSpecification *>();
    qRegisterMetaType<QList<QOccurrenceSpecification *>>();
    qRegisterMetaType<QSet<QOccurrenceSpecification *>>();
    qRegisterMetaType<QOpaqueAction *>();
    qRegisterMetaType<QList<QOpaqueAction *>>();
    qRegisterMetaType<QSet<QOpaqueAction *>>();
    qRegisterMetaType<QOpaqueBehavior *>();
    qRegisterMetaType<QList<QOpaqueBehavior *>>();
    qRegisterMetaType<QSet<QOpaqueBehavior *>>();
    qRegisterMetaType<QOpaqueExpression *>();
    qRegisterMetaType<QList<QOpaqueExpression *>>();
    qRegisterMetaType<QSet<QOpaqueExpression *>>();
    qRegisterMetaType<QOperation *>();
    qRegisterMetaType<QList<QOperation *>>();
    qRegisterMetaType<QSet<QOperation *>>();
    qRegisterMetaType<QOperationTemplateParameter *>();
    qRegisterMetaType<QList<QOperationTemplateParameter *>>();
    qRegisterMetaType<QSet<QOperationTemplateParameter *>>();
    qRegisterMetaType<QOutputPin *>();
    qRegisterMetaType<QList<QOutputPin *>>();
    qRegisterMetaType<QSet<QOutputPin *>>();
    qRegisterMetaType<QPackage *>();
    qRegisterMetaType<QList<QPackage *>>();
    qRegisterMetaType<QSet<QPackage *>>();
    qRegisterMetaType<QPackageImport *>();
    qRegisterMetaType<QList<QPackageImport *>>();
    qRegisterMetaType<QSet<QPackageImport *>>();
    qRegisterMetaType<QPackageMerge *>();
    qRegisterMetaType<QList<QPackageMerge *>>();
    qRegisterMetaType<QSet<QPackageMerge *>>();
    qRegisterMetaType<QPackageableElement *>();
    qRegisterMetaType<QList<QPackageableElement *>>();
    qRegisterMetaType<QSet<QPackageableElement *>>();
    qRegisterMetaType<QParameter *>();
    qRegisterMetaType<QList<QParameter *>>();
    qRegisterMetaType<QSet<QParameter *>>();
    qRegisterMetaType<QParameterSet *>();
    qRegisterMetaType<QList<QParameterSet *>>();
    qRegisterMetaType<QSet<QParameterSet *>>();
    qRegisterMetaType<QParameterableElement *>();
    qRegisterMetaType<QList<QParameterableElement *>>();
    qRegisterMetaType<QSet<QParameterableElement *>>();
    qRegisterMetaType<QPartDecomposition *>();
    qRegisterMetaType<QList<QPartDecomposition *>>();
    qRegisterMetaType<QSet<QPartDecomposition *>>();
    qRegisterMetaType<QPin *>();
    qRegisterMetaType<QList<QPin *>>();
    qRegisterMetaType<QSet<QPin *>>();
    qRegisterMetaType<QPort *>();
    qRegisterMetaType<QList<QPort *>>();
    qRegisterMetaType<QSet<QPort *>>();
    qRegisterMetaType<QPrimitiveType *>();
    qRegisterMetaType<QList<QPrimitiveType *>>();
    qRegisterMetaType<QSet<QPrimitiveType *>>();
    qRegisterMetaType<QProfile *>();
    qRegisterMetaType<QList<QProfile *>>();
    qRegisterMetaType<QSet<QProfile *>>();
    qRegisterMetaType<QProfileApplication *>();
    qRegisterMetaType<QList<QProfileApplication *>>();
    qRegisterMetaType<QSet<QProfileApplication *>>();
    qRegisterMetaType<QProperty *>();
    qRegisterMetaType<QList<QProperty *>>();
    qRegisterMetaType<QSet<QProperty *>>();
    qRegisterMetaType<QProtocolConformance *>();
    qRegisterMetaType<QList<QProtocolConformance *>>();
    qRegisterMetaType<QSet<QProtocolConformance *>>();
    qRegisterMetaType<QProtocolStateMachine *>();
    qRegisterMetaType<QList<QProtocolStateMachine *>>();
    qRegisterMetaType<QSet<QProtocolStateMachine *>>();
    qRegisterMetaType<QProtocolTransition *>();
    qRegisterMetaType<QList<QProtocolTransition *>>();
    qRegisterMetaType<QSet<QProtocolTransition *>>();
    qRegisterMetaType<QPseudostate *>();
    qRegisterMetaType<QList<QPseudostate *>>();
    qRegisterMetaType<QSet<QPseudostate *>>();
    qRegisterMetaType<QQualifierValue *>();
    qRegisterMetaType<QList<QQualifierValue *>>();
    qRegisterMetaType<QSet<QQualifierValue *>>();
    qRegisterMetaType<QRaiseExceptionAction *>();
    qRegisterMetaType<QList<QRaiseExceptionAction *>>();
    qRegisterMetaType<QSet<QRaiseExceptionAction *>>();
    qRegisterMetaType<QReadExtentAction *>();
    qRegisterMetaType<QList<QReadExtentAction *>>();
    qRegisterMetaType<QSet<QReadExtentAction *>>();
    qRegisterMetaType<QReadIsClassifiedObjectAction *>();
    qRegisterMetaType<QList<QReadIsClassifiedObjectAction *>>();
    qRegisterMetaType<QSet<QReadIsClassifiedObjectAction *>>();
    qRegisterMetaType<QReadLinkAction *>();
    qRegisterMetaType<QList<QReadLinkAction *>>();
    qRegisterMetaType<QSet<QReadLinkAction *>>();
    qRegisterMetaType<QReadLinkObjectEndAction *>();
    qRegisterMetaType<QList<QReadLinkObjectEndAction *>>();
    qRegisterMetaType<QSet<QReadLinkObjectEndAction *>>();
    qRegisterMetaType<QReadLinkObjectEndQualifierAction *>();
    qRegisterMetaType<QList<QReadLinkObjectEndQualifierAction *>>();
    qRegisterMetaType<QSet<QReadLinkObjectEndQualifierAction *>>();
    qRegisterMetaType<QReadSelfAction *>();
    qRegisterMetaType<QList<QReadSelfAction *>>();
    qRegisterMetaType<QSet<QReadSelfAction *>>();
    qRegisterMetaType<QReadStructuralFeatureAction *>();
    qRegisterMetaType<QList<QReadStructuralFeatureAction *>>();
    qRegisterMetaType<QSet<QReadStructuralFeatureAction *>>();
    qRegisterMetaType<QReadVariableAction *>();
    qRegisterMetaType<QList<QReadVariableAction *>>();
    qRegisterMetaType<QSet<QReadVariableAction *>>();
    qRegisterMetaType<QRealization *>();
    qRegisterMetaType<QList<QRealization *>>();
    qRegisterMetaType<QSet<QRealization *>>();
    qRegisterMetaType<QReception *>();
    qRegisterMetaType<QList<QReception *>>();
    qRegisterMetaType<QSet<QReception *>>();
    qRegisterMetaType<QReclassifyObjectAction *>();
    qRegisterMetaType<QList<QReclassifyObjectAction *>>();
    qRegisterMetaType<QSet<QReclassifyObjectAction *>>();
    qRegisterMetaType<QRedefinableElement *>();
    qRegisterMetaType<QList<QRedefinableElement *>>();
    qRegisterMetaType<QSet<QRedefinableElement *>>();
    qRegisterMetaType<QRedefinableTemplateSignature *>();
    qRegisterMetaType<QList<QRedefinableTemplateSignature *>>();
    qRegisterMetaType<QSet<QRedefinableTemplateSignature *>>();
    qRegisterMetaType<QReduceAction *>();
    qRegisterMetaType<QList<QReduceAction *>>();
    qRegisterMetaType<QSet<QReduceAction *>>();
    qRegisterMetaType<QRegion *>();
    qRegisterMetaType<QList<QRegion *>>();
    qRegisterMetaType<QSet<QRegion *>>();
    qRegisterMetaType<QRelationship *>();
    qRegisterMetaType<QList<QRelationship *>>();
    qRegisterMetaType<QSet<QRelationship *>>();
    qRegisterMetaType<QRemoveStructuralFeatureValueAction *>();
    qRegisterMetaType<QList<QRemoveStructuralFeatureValueAction *>>();
    qRegisterMetaType<QSet<QRemoveStructuralFeatureValueAction *>>();
    qRegisterMetaType<QRemoveVariableValueAction *>();
    qRegisterMetaType<QList<QRemoveVariableValueAction *>>();
    qRegisterMetaType<QSet<QRemoveVariableValueAction *>>();
    qRegisterMetaType<QReplyAction *>();
    qRegisterMetaType<QList<QReplyAction *>>();
    qRegisterMetaType<QSet<QReplyAction *>>();
    qRegisterMetaType<QSendObjectAction *>();
    qRegisterMetaType<QList<QSendObjectAction *>>();
    qRegisterMetaType<QSet<QSendObjectAction *>>();
    qRegisterMetaType<QSendSignalAction *>();
    qRegisterMetaType<QList<QSendSignalAction *>>();
    qRegisterMetaType<QSet<QSendSignalAction *>>();
    qRegisterMetaType<QSequenceNode *>();
    qRegisterMetaType<QList<QSequenceNode *>>();
    qRegisterMetaType<QSet<QSequenceNode *>>();
    qRegisterMetaType<QSignal *>();
    qRegisterMetaType<QList<QSignal *>>();
    qRegisterMetaType<QSet<QSignal *>>();
    qRegisterMetaType<QSignalEvent *>();
    qRegisterMetaType<QList<QSignalEvent *>>();
    qRegisterMetaType<QSet<QSignalEvent *>>();
    qRegisterMetaType<QSlot *>();
    qRegisterMetaType<QList<QSlot *>>();
    qRegisterMetaType<QSet<QSlot *>>();
    qRegisterMetaType<QStartClassifierBehaviorAction *>();
    qRegisterMetaType<QList<QStartClassifierBehaviorAction *>>();
    qRegisterMetaType<QSet<QStartClassifierBehaviorAction *>>();
    qRegisterMetaType<QStartObjectBehaviorAction *>();
    qRegisterMetaType<QList<QStartObjectBehaviorAction *>>();
    qRegisterMetaType<QSet<QStartObjectBehaviorAction *>>();
    qRegisterMetaType<QState *>();
    qRegisterMetaType<QList<QState *>>();
    qRegisterMetaType<QSet<QState *>>();
    qRegisterMetaType<QStateInvariant *>();
    qRegisterMetaType<QList<QStateInvariant *>>();
    qRegisterMetaType<QSet<QStateInvariant *>>();
    qRegisterMetaType<QStateMachine *>();
    qRegisterMetaType<QList<QStateMachine *>>();
    qRegisterMetaType<QSet<QStateMachine *>>();
    qRegisterMetaType<QStereotype *>();
    qRegisterMetaType<QList<QStereotype *>>();
    qRegisterMetaType<QSet<QStereotype *>>();
    qRegisterMetaType<QStringExpression *>();
    qRegisterMetaType<QList<QStringExpression *>>();
    qRegisterMetaType<QSet<QStringExpression *>>();
    qRegisterMetaType<QStructuralFeature *>();
    qRegisterMetaType<QList<QStructuralFeature *>>();
    qRegisterMetaType<QSet<QStructuralFeature *>>();
    qRegisterMetaType<QStructuralFeatureAction *>();
    qRegisterMetaType<QList<QStructuralFeatureAction *>>();
    qRegisterMetaType<QSet<QStructuralFeatureAction *>>();
    qRegisterMetaType<QStructuredActivityNode *>();
    qRegisterMetaType<QList<QStructuredActivityNode *>>();
    qRegisterMetaType<QSet<QStructuredActivityNode *>>();
    qRegisterMetaType<QStructuredClassifier *>();
    qRegisterMetaType<QList<QStructuredClassifier *>>();
    qRegisterMetaType<QSet<QStructuredClassifier *>>();
    qRegisterMetaType<QSubstitution *>();
    qRegisterMetaType<QList<QSubstitution *>>();
    qRegisterMetaType<QSet<QSubstitution *>>();
    qRegisterMetaType<QTemplateBinding *>();
    qRegisterMetaType<QList<QTemplateBinding *>>();
    qRegisterMetaType<QSet<QTemplateBinding *>>();
    qRegisterMetaType<QTemplateParameter *>();
    qRegisterMetaType<QList<QTemplateParameter *>>();
    qRegisterMetaType<QSet<QTemplateParameter *>>();
    qRegisterMetaType<QTemplateParameterSubstitution *>();
    qRegisterMetaType<QList<QTemplateParameterSubstitution *>>();
    qRegisterMetaType<QSet<QTemplateParameterSubstitution *>>();
    qRegisterMetaType<QTemplateSignature *>();
    qRegisterMetaType<QList<QTemplateSignature *>>();
    qRegisterMetaType<QSet<QTemplateSignature *>>();
    qRegisterMetaType<QTemplateableElement *>();
    qRegisterMetaType<QList<QTemplateableElement *>>();
    qRegisterMetaType<QSet<QTemplateableElement *>>();
    qRegisterMetaType<QTestIdentityAction *>();
    qRegisterMetaType<QList<QTestIdentityAction *>>();
    qRegisterMetaType<QSet<QTestIdentityAction *>>();
    qRegisterMetaType<QTimeConstraint *>();
    qRegisterMetaType<QList<QTimeConstraint *>>();
    qRegisterMetaType<QSet<QTimeConstraint *>>();
    qRegisterMetaType<QTimeEvent *>();
    qRegisterMetaType<QList<QTimeEvent *>>();
    qRegisterMetaType<QSet<QTimeEvent *>>();
    qRegisterMetaType<QTimeExpression *>();
    qRegisterMetaType<QList<QTimeExpression *>>();
    qRegisterMetaType<QSet<QTimeExpression *>>();
    qRegisterMetaType<QTimeInterval *>();
    qRegisterMetaType<QList<QTimeInterval *>>();
    qRegisterMetaType<QSet<QTimeInterval *>>();
    qRegisterMetaType<QTimeObservation *>();
    qRegisterMetaType<QList<QTimeObservation *>>();
    qRegisterMetaType<QSet<QTimeObservation *>>();
    qRegisterMetaType<QTransition *>();
    qRegisterMetaType<QList<QTransition *>>();
    qRegisterMetaType<QSet<QTransition *>>();
    qRegisterMetaType<QTrigger *>();
    qRegisterMetaType<QList<QTrigger *>>();
    qRegisterMetaType<QSet<QTrigger *>>();
    qRegisterMetaType<QType *>();
    qRegisterMetaType<QList<QType *>>();
    qRegisterMetaType<QSet<QType *>>();
    qRegisterMetaType<QTypedElement *>();
    qRegisterMetaType<QList<QTypedElement *>>();
    qRegisterMetaType<QSet<QTypedElement *>>();
    qRegisterMetaType<QUnmarshallAction *>();
    qRegisterMetaType<QList<QUnmarshallAction *>>();
    qRegisterMetaType<QSet<QUnmarshallAction *>>();
    qRegisterMetaType<QUsage *>();
    qRegisterMetaType<QList<QUsage *>>();
    qRegisterMetaType<QSet<QUsage *>>();
    qRegisterMetaType<QUseCase *>();
    qRegisterMetaType<QList<QUseCase *>>();
    qRegisterMetaType<QSet<QUseCase *>>();
    qRegisterMetaType<QValuePin *>();
    qRegisterMetaType<QList<QValuePin *>>();
    qRegisterMetaType<QSet<QValuePin *>>();
    qRegisterMetaType<QValueSpecification *>();
    qRegisterMetaType<QList<QValueSpecification *>>();
    qRegisterMetaType<QSet<QValueSpecification *>>();
    qRegisterMetaType<QValueSpecificationAction *>();
    qRegisterMetaType<QList<QValueSpecificationAction *>>();
    qRegisterMetaType<QSet<QValueSpecificationAction *>>();
    qRegisterMetaType<QVariable *>();
    qRegisterMetaType<QList<QVariable *>>();
    qRegisterMetaType<QSet<QVariable *>>();
    qRegisterMetaType<QVariableAction *>();
    qRegisterMetaType<QList<QVariableAction *>>();
    qRegisterMetaType<QSet<QVariableAction *>>();
    qRegisterMetaType<QVertex *>();
    qRegisterMetaType<QList<QVertex *>>();
    qRegisterMetaType<QSet<QVertex *>>();
    qRegisterMetaType<QWriteLinkAction *>();
    qRegisterMetaType<QList<QWriteLinkAction *>>();
    qRegisterMetaType<QSet<QWriteLinkAction *>>();
    qRegisterMetaType<QWriteStructuralFeatureAction *>();
    qRegisterMetaType<QList<QWriteStructuralFeatureAction *>>();
    qRegisterMetaType<QSet<QWriteStructuralFeatureAction *>>();
    qRegisterMetaType<QWriteVariableAction *>();
    qRegisterMetaType<QList<QWriteVariableAction *>>();
    qRegisterMetaType<QSet<QWriteVariableAction *>>();

    if (scriptEngine) {
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QAbstraction>, scriptValueToQSet<QAbstraction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QAbstraction>, scriptValueToQList<QAbstraction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QAcceptCallAction>, scriptValueToQSet<QAcceptCallAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QAcceptCallAction>, scriptValueToQList<QAcceptCallAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QAcceptEventAction>, scriptValueToQSet<QAcceptEventAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QAcceptEventAction>, scriptValueToQList<QAcceptEventAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QAction>, scriptValueToQSet<QAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QAction>, scriptValueToQList<QAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QActionExecutionSpecification>, scriptValueToQSet<QActionExecutionSpecification>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QActionExecutionSpecification>, scriptValueToQList<QActionExecutionSpecification>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QActionInputPin>, scriptValueToQSet<QActionInputPin>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QActionInputPin>, scriptValueToQList<QActionInputPin>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QActivity>, scriptValueToQSet<QActivity>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QActivity>, scriptValueToQList<QActivity>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QActivityEdge>, scriptValueToQSet<QActivityEdge>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QActivityEdge>, scriptValueToQList<QActivityEdge>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QActivityFinalNode>, scriptValueToQSet<QActivityFinalNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QActivityFinalNode>, scriptValueToQList<QActivityFinalNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QActivityGroup>, scriptValueToQSet<QActivityGroup>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QActivityGroup>, scriptValueToQList<QActivityGroup>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QActivityNode>, scriptValueToQSet<QActivityNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QActivityNode>, scriptValueToQList<QActivityNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QActivityParameterNode>, scriptValueToQSet<QActivityParameterNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QActivityParameterNode>, scriptValueToQList<QActivityParameterNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QActivityPartition>, scriptValueToQSet<QActivityPartition>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QActivityPartition>, scriptValueToQList<QActivityPartition>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QActor>, scriptValueToQSet<QActor>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QActor>, scriptValueToQList<QActor>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QAddStructuralFeatureValueAction>, scriptValueToQSet<QAddStructuralFeatureValueAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QAddStructuralFeatureValueAction>, scriptValueToQList<QAddStructuralFeatureValueAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QAddVariableValueAction>, scriptValueToQSet<QAddVariableValueAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QAddVariableValueAction>, scriptValueToQList<QAddVariableValueAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QAnyReceiveEvent>, scriptValueToQSet<QAnyReceiveEvent>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QAnyReceiveEvent>, scriptValueToQList<QAnyReceiveEvent>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QArtifact>, scriptValueToQSet<QArtifact>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QArtifact>, scriptValueToQList<QArtifact>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QAssociation>, scriptValueToQSet<QAssociation>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QAssociation>, scriptValueToQList<QAssociation>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QAssociationClass>, scriptValueToQSet<QAssociationClass>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QAssociationClass>, scriptValueToQList<QAssociationClass>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QBehavior>, scriptValueToQSet<QBehavior>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QBehavior>, scriptValueToQList<QBehavior>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QBehavioralFeature>, scriptValueToQSet<QBehavioralFeature>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QBehavioralFeature>, scriptValueToQList<QBehavioralFeature>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QBehavioredClassifier>, scriptValueToQSet<QBehavioredClassifier>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QBehavioredClassifier>, scriptValueToQList<QBehavioredClassifier>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QBehaviorExecutionSpecification>, scriptValueToQSet<QBehaviorExecutionSpecification>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QBehaviorExecutionSpecification>, scriptValueToQList<QBehaviorExecutionSpecification>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QBroadcastSignalAction>, scriptValueToQSet<QBroadcastSignalAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QBroadcastSignalAction>, scriptValueToQList<QBroadcastSignalAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCallAction>, scriptValueToQSet<QCallAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCallAction>, scriptValueToQList<QCallAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCallBehaviorAction>, scriptValueToQSet<QCallBehaviorAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCallBehaviorAction>, scriptValueToQList<QCallBehaviorAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCallEvent>, scriptValueToQSet<QCallEvent>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCallEvent>, scriptValueToQList<QCallEvent>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCallOperationAction>, scriptValueToQSet<QCallOperationAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCallOperationAction>, scriptValueToQList<QCallOperationAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCentralBufferNode>, scriptValueToQSet<QCentralBufferNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCentralBufferNode>, scriptValueToQList<QCentralBufferNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QChangeEvent>, scriptValueToQSet<QChangeEvent>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QChangeEvent>, scriptValueToQList<QChangeEvent>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QClass>, scriptValueToQSet<QClass>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QClass>, scriptValueToQList<QClass>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QClassifier>, scriptValueToQSet<QClassifier>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QClassifier>, scriptValueToQList<QClassifier>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QClassifierTemplateParameter>, scriptValueToQSet<QClassifierTemplateParameter>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QClassifierTemplateParameter>, scriptValueToQList<QClassifierTemplateParameter>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QClause>, scriptValueToQSet<QClause>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QClause>, scriptValueToQList<QClause>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QClearAssociationAction>, scriptValueToQSet<QClearAssociationAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QClearAssociationAction>, scriptValueToQList<QClearAssociationAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QClearStructuralFeatureAction>, scriptValueToQSet<QClearStructuralFeatureAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QClearStructuralFeatureAction>, scriptValueToQList<QClearStructuralFeatureAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QClearVariableAction>, scriptValueToQSet<QClearVariableAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QClearVariableAction>, scriptValueToQList<QClearVariableAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCollaboration>, scriptValueToQSet<QCollaboration>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCollaboration>, scriptValueToQList<QCollaboration>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCollaborationUse>, scriptValueToQSet<QCollaborationUse>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCollaborationUse>, scriptValueToQList<QCollaborationUse>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCombinedFragment>, scriptValueToQSet<QCombinedFragment>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCombinedFragment>, scriptValueToQList<QCombinedFragment>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QComment>, scriptValueToQSet<QComment>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QComment>, scriptValueToQList<QComment>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCommunicationPath>, scriptValueToQSet<QCommunicationPath>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCommunicationPath>, scriptValueToQList<QCommunicationPath>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QComponent>, scriptValueToQSet<QComponent>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QComponent>, scriptValueToQList<QComponent>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QComponentRealization>, scriptValueToQSet<QComponentRealization>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QComponentRealization>, scriptValueToQList<QComponentRealization>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QConditionalNode>, scriptValueToQSet<QConditionalNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QConditionalNode>, scriptValueToQList<QConditionalNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QConnectableElement>, scriptValueToQSet<QConnectableElement>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QConnectableElement>, scriptValueToQList<QConnectableElement>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QConnectableElementTemplateParameter>, scriptValueToQSet<QConnectableElementTemplateParameter>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QConnectableElementTemplateParameter>, scriptValueToQList<QConnectableElementTemplateParameter>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QConnectionPointReference>, scriptValueToQSet<QConnectionPointReference>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QConnectionPointReference>, scriptValueToQList<QConnectionPointReference>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QConnector>, scriptValueToQSet<QConnector>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QConnector>, scriptValueToQList<QConnector>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QConnectorEnd>, scriptValueToQSet<QConnectorEnd>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QConnectorEnd>, scriptValueToQList<QConnectorEnd>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QConsiderIgnoreFragment>, scriptValueToQSet<QConsiderIgnoreFragment>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QConsiderIgnoreFragment>, scriptValueToQList<QConsiderIgnoreFragment>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QConstraint>, scriptValueToQSet<QConstraint>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QConstraint>, scriptValueToQList<QConstraint>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QContinuation>, scriptValueToQSet<QContinuation>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QContinuation>, scriptValueToQList<QContinuation>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QControlFlow>, scriptValueToQSet<QControlFlow>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QControlFlow>, scriptValueToQList<QControlFlow>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QControlNode>, scriptValueToQSet<QControlNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QControlNode>, scriptValueToQList<QControlNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCreateLinkAction>, scriptValueToQSet<QCreateLinkAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCreateLinkAction>, scriptValueToQList<QCreateLinkAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCreateLinkObjectAction>, scriptValueToQSet<QCreateLinkObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCreateLinkObjectAction>, scriptValueToQList<QCreateLinkObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QCreateObjectAction>, scriptValueToQSet<QCreateObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QCreateObjectAction>, scriptValueToQList<QCreateObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDataStoreNode>, scriptValueToQSet<QDataStoreNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDataStoreNode>, scriptValueToQList<QDataStoreNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDataType>, scriptValueToQSet<QDataType>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDataType>, scriptValueToQList<QDataType>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDecisionNode>, scriptValueToQSet<QDecisionNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDecisionNode>, scriptValueToQList<QDecisionNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDependency>, scriptValueToQSet<QDependency>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDependency>, scriptValueToQList<QDependency>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDeployedArtifact>, scriptValueToQSet<QDeployedArtifact>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDeployedArtifact>, scriptValueToQList<QDeployedArtifact>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDeployment>, scriptValueToQSet<QDeployment>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDeployment>, scriptValueToQList<QDeployment>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDeploymentSpecification>, scriptValueToQSet<QDeploymentSpecification>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDeploymentSpecification>, scriptValueToQList<QDeploymentSpecification>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDeploymentTarget>, scriptValueToQSet<QDeploymentTarget>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDeploymentTarget>, scriptValueToQList<QDeploymentTarget>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDestroyLinkAction>, scriptValueToQSet<QDestroyLinkAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDestroyLinkAction>, scriptValueToQList<QDestroyLinkAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDestroyObjectAction>, scriptValueToQSet<QDestroyObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDestroyObjectAction>, scriptValueToQList<QDestroyObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDestructionOccurrenceSpecification>, scriptValueToQSet<QDestructionOccurrenceSpecification>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDestructionOccurrenceSpecification>, scriptValueToQList<QDestructionOccurrenceSpecification>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDevice>, scriptValueToQSet<QDevice>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDevice>, scriptValueToQList<QDevice>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDirectedRelationship>, scriptValueToQSet<QDirectedRelationship>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDirectedRelationship>, scriptValueToQList<QDirectedRelationship>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDuration>, scriptValueToQSet<QDuration>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDuration>, scriptValueToQList<QDuration>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDurationConstraint>, scriptValueToQSet<QDurationConstraint>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDurationConstraint>, scriptValueToQList<QDurationConstraint>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDurationInterval>, scriptValueToQSet<QDurationInterval>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDurationInterval>, scriptValueToQList<QDurationInterval>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QDurationObservation>, scriptValueToQSet<QDurationObservation>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QDurationObservation>, scriptValueToQList<QDurationObservation>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QElement>, scriptValueToQSet<QElement>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QElement>, scriptValueToQList<QElement>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QElementImport>, scriptValueToQSet<QElementImport>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QElementImport>, scriptValueToQList<QElementImport>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QEncapsulatedClassifier>, scriptValueToQSet<QEncapsulatedClassifier>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QEncapsulatedClassifier>, scriptValueToQList<QEncapsulatedClassifier>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QEnumeration>, scriptValueToQSet<QEnumeration>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QEnumeration>, scriptValueToQList<QEnumeration>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QEnumerationLiteral>, scriptValueToQSet<QEnumerationLiteral>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QEnumerationLiteral>, scriptValueToQList<QEnumerationLiteral>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QEvent>, scriptValueToQSet<QEvent>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QEvent>, scriptValueToQList<QEvent>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExceptionHandler>, scriptValueToQSet<QExceptionHandler>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExceptionHandler>, scriptValueToQList<QExceptionHandler>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExecutableNode>, scriptValueToQSet<QExecutableNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExecutableNode>, scriptValueToQList<QExecutableNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExecutionEnvironment>, scriptValueToQSet<QExecutionEnvironment>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExecutionEnvironment>, scriptValueToQList<QExecutionEnvironment>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExecutionOccurrenceSpecification>, scriptValueToQSet<QExecutionOccurrenceSpecification>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExecutionOccurrenceSpecification>, scriptValueToQList<QExecutionOccurrenceSpecification>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExecutionSpecification>, scriptValueToQSet<QExecutionSpecification>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExecutionSpecification>, scriptValueToQList<QExecutionSpecification>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExpansionNode>, scriptValueToQSet<QExpansionNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExpansionNode>, scriptValueToQList<QExpansionNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExpansionRegion>, scriptValueToQSet<QExpansionRegion>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExpansionRegion>, scriptValueToQList<QExpansionRegion>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExpression>, scriptValueToQSet<QExpression>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExpression>, scriptValueToQList<QExpression>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExtend>, scriptValueToQSet<QExtend>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExtend>, scriptValueToQList<QExtend>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExtension>, scriptValueToQSet<QExtension>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExtension>, scriptValueToQList<QExtension>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExtensionEnd>, scriptValueToQSet<QExtensionEnd>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExtensionEnd>, scriptValueToQList<QExtensionEnd>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QExtensionPoint>, scriptValueToQSet<QExtensionPoint>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QExtensionPoint>, scriptValueToQList<QExtensionPoint>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QFeature>, scriptValueToQSet<QFeature>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QFeature>, scriptValueToQList<QFeature>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QFinalNode>, scriptValueToQSet<QFinalNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QFinalNode>, scriptValueToQList<QFinalNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QFinalState>, scriptValueToQSet<QFinalState>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QFinalState>, scriptValueToQList<QFinalState>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QFlowFinalNode>, scriptValueToQSet<QFlowFinalNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QFlowFinalNode>, scriptValueToQList<QFlowFinalNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QForkNode>, scriptValueToQSet<QForkNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QForkNode>, scriptValueToQList<QForkNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QFunctionBehavior>, scriptValueToQSet<QFunctionBehavior>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QFunctionBehavior>, scriptValueToQList<QFunctionBehavior>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QGate>, scriptValueToQSet<QGate>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QGate>, scriptValueToQList<QGate>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QGeneralization>, scriptValueToQSet<QGeneralization>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QGeneralization>, scriptValueToQList<QGeneralization>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QGeneralizationSet>, scriptValueToQSet<QGeneralizationSet>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QGeneralizationSet>, scriptValueToQList<QGeneralizationSet>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QGeneralOrdering>, scriptValueToQSet<QGeneralOrdering>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QGeneralOrdering>, scriptValueToQList<QGeneralOrdering>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QImage>, scriptValueToQSet<QImage>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QImage>, scriptValueToQList<QImage>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInclude>, scriptValueToQSet<QInclude>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInclude>, scriptValueToQList<QInclude>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInformationFlow>, scriptValueToQSet<QInformationFlow>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInformationFlow>, scriptValueToQList<QInformationFlow>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInformationItem>, scriptValueToQSet<QInformationItem>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInformationItem>, scriptValueToQList<QInformationItem>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInitialNode>, scriptValueToQSet<QInitialNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInitialNode>, scriptValueToQList<QInitialNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInputPin>, scriptValueToQSet<QInputPin>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInputPin>, scriptValueToQList<QInputPin>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInstanceSpecification>, scriptValueToQSet<QInstanceSpecification>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInstanceSpecification>, scriptValueToQList<QInstanceSpecification>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInstanceValue>, scriptValueToQSet<QInstanceValue>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInstanceValue>, scriptValueToQList<QInstanceValue>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInteraction>, scriptValueToQSet<QInteraction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInteraction>, scriptValueToQList<QInteraction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInteractionConstraint>, scriptValueToQSet<QInteractionConstraint>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInteractionConstraint>, scriptValueToQList<QInteractionConstraint>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInteractionFragment>, scriptValueToQSet<QInteractionFragment>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInteractionFragment>, scriptValueToQList<QInteractionFragment>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInteractionOperand>, scriptValueToQSet<QInteractionOperand>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInteractionOperand>, scriptValueToQList<QInteractionOperand>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInteractionUse>, scriptValueToQSet<QInteractionUse>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInteractionUse>, scriptValueToQList<QInteractionUse>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInterface>, scriptValueToQSet<QInterface>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInterface>, scriptValueToQList<QInterface>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInterfaceRealization>, scriptValueToQSet<QInterfaceRealization>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInterfaceRealization>, scriptValueToQList<QInterfaceRealization>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInterruptibleActivityRegion>, scriptValueToQSet<QInterruptibleActivityRegion>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInterruptibleActivityRegion>, scriptValueToQList<QInterruptibleActivityRegion>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInterval>, scriptValueToQSet<QInterval>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInterval>, scriptValueToQList<QInterval>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QIntervalConstraint>, scriptValueToQSet<QIntervalConstraint>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QIntervalConstraint>, scriptValueToQList<QIntervalConstraint>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QInvocationAction>, scriptValueToQSet<QInvocationAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QInvocationAction>, scriptValueToQList<QInvocationAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QJoinNode>, scriptValueToQSet<QJoinNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QJoinNode>, scriptValueToQList<QJoinNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLifeline>, scriptValueToQSet<QLifeline>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLifeline>, scriptValueToQList<QLifeline>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLinkAction>, scriptValueToQSet<QLinkAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLinkAction>, scriptValueToQList<QLinkAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLinkEndCreationData>, scriptValueToQSet<QLinkEndCreationData>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLinkEndCreationData>, scriptValueToQList<QLinkEndCreationData>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLinkEndData>, scriptValueToQSet<QLinkEndData>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLinkEndData>, scriptValueToQList<QLinkEndData>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLinkEndDestructionData>, scriptValueToQSet<QLinkEndDestructionData>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLinkEndDestructionData>, scriptValueToQList<QLinkEndDestructionData>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLiteralBoolean>, scriptValueToQSet<QLiteralBoolean>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLiteralBoolean>, scriptValueToQList<QLiteralBoolean>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLiteralInteger>, scriptValueToQSet<QLiteralInteger>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLiteralInteger>, scriptValueToQList<QLiteralInteger>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLiteralNull>, scriptValueToQSet<QLiteralNull>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLiteralNull>, scriptValueToQList<QLiteralNull>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLiteralReal>, scriptValueToQSet<QLiteralReal>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLiteralReal>, scriptValueToQList<QLiteralReal>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLiteralSpecification>, scriptValueToQSet<QLiteralSpecification>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLiteralSpecification>, scriptValueToQList<QLiteralSpecification>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLiteralString>, scriptValueToQSet<QLiteralString>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLiteralString>, scriptValueToQList<QLiteralString>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLiteralUnlimitedNatural>, scriptValueToQSet<QLiteralUnlimitedNatural>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLiteralUnlimitedNatural>, scriptValueToQList<QLiteralUnlimitedNatural>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QLoopNode>, scriptValueToQSet<QLoopNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QLoopNode>, scriptValueToQList<QLoopNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QManifestation>, scriptValueToQSet<QManifestation>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QManifestation>, scriptValueToQList<QManifestation>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QMergeNode>, scriptValueToQSet<QMergeNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QMergeNode>, scriptValueToQList<QMergeNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QMessage>, scriptValueToQSet<QMessage>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QMessage>, scriptValueToQList<QMessage>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QMessageEnd>, scriptValueToQSet<QMessageEnd>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QMessageEnd>, scriptValueToQList<QMessageEnd>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QMessageEvent>, scriptValueToQSet<QMessageEvent>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QMessageEvent>, scriptValueToQList<QMessageEvent>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QMessageOccurrenceSpecification>, scriptValueToQSet<QMessageOccurrenceSpecification>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QMessageOccurrenceSpecification>, scriptValueToQList<QMessageOccurrenceSpecification>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QModel>, scriptValueToQSet<QModel>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QModel>, scriptValueToQList<QModel>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QMultiplicityElement>, scriptValueToQSet<QMultiplicityElement>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QMultiplicityElement>, scriptValueToQList<QMultiplicityElement>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QNamedElement>, scriptValueToQSet<QNamedElement>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QNamedElement>, scriptValueToQList<QNamedElement>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QNamespace>, scriptValueToQSet<QNamespace>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QNamespace>, scriptValueToQList<QNamespace>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QNode>, scriptValueToQSet<QNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QNode>, scriptValueToQList<QNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QObjectFlow>, scriptValueToQSet<QObjectFlow>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QObjectFlow>, scriptValueToQList<QObjectFlow>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QObjectNode>, scriptValueToQSet<QObjectNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QObjectNode>, scriptValueToQList<QObjectNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QObservation>, scriptValueToQSet<QObservation>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QObservation>, scriptValueToQList<QObservation>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QOccurrenceSpecification>, scriptValueToQSet<QOccurrenceSpecification>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QOccurrenceSpecification>, scriptValueToQList<QOccurrenceSpecification>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QOpaqueAction>, scriptValueToQSet<QOpaqueAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QOpaqueAction>, scriptValueToQList<QOpaqueAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QOpaqueBehavior>, scriptValueToQSet<QOpaqueBehavior>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QOpaqueBehavior>, scriptValueToQList<QOpaqueBehavior>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QOpaqueExpression>, scriptValueToQSet<QOpaqueExpression>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QOpaqueExpression>, scriptValueToQList<QOpaqueExpression>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QOperation>, scriptValueToQSet<QOperation>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QOperation>, scriptValueToQList<QOperation>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QOperationTemplateParameter>, scriptValueToQSet<QOperationTemplateParameter>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QOperationTemplateParameter>, scriptValueToQList<QOperationTemplateParameter>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QOutputPin>, scriptValueToQSet<QOutputPin>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QOutputPin>, scriptValueToQList<QOutputPin>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QPackage>, scriptValueToQSet<QPackage>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QPackage>, scriptValueToQList<QPackage>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QPackageableElement>, scriptValueToQSet<QPackageableElement>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QPackageableElement>, scriptValueToQList<QPackageableElement>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QPackageImport>, scriptValueToQSet<QPackageImport>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QPackageImport>, scriptValueToQList<QPackageImport>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QPackageMerge>, scriptValueToQSet<QPackageMerge>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QPackageMerge>, scriptValueToQList<QPackageMerge>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QParameter>, scriptValueToQSet<QParameter>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QParameter>, scriptValueToQList<QParameter>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QParameterableElement>, scriptValueToQSet<QParameterableElement>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QParameterableElement>, scriptValueToQList<QParameterableElement>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QParameterSet>, scriptValueToQSet<QParameterSet>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QParameterSet>, scriptValueToQList<QParameterSet>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QPartDecomposition>, scriptValueToQSet<QPartDecomposition>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QPartDecomposition>, scriptValueToQList<QPartDecomposition>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QPin>, scriptValueToQSet<QPin>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QPin>, scriptValueToQList<QPin>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QPort>, scriptValueToQSet<QPort>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QPort>, scriptValueToQList<QPort>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QPrimitiveType>, scriptValueToQSet<QPrimitiveType>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QPrimitiveType>, scriptValueToQList<QPrimitiveType>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QProfile>, scriptValueToQSet<QProfile>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QProfile>, scriptValueToQList<QProfile>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QProfileApplication>, scriptValueToQSet<QProfileApplication>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QProfileApplication>, scriptValueToQList<QProfileApplication>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QProperty>, scriptValueToQSet<QProperty>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QProperty>, scriptValueToQList<QProperty>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QProtocolConformance>, scriptValueToQSet<QProtocolConformance>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QProtocolConformance>, scriptValueToQList<QProtocolConformance>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QProtocolStateMachine>, scriptValueToQSet<QProtocolStateMachine>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QProtocolStateMachine>, scriptValueToQList<QProtocolStateMachine>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QProtocolTransition>, scriptValueToQSet<QProtocolTransition>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QProtocolTransition>, scriptValueToQList<QProtocolTransition>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QPseudostate>, scriptValueToQSet<QPseudostate>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QPseudostate>, scriptValueToQList<QPseudostate>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QQualifierValue>, scriptValueToQSet<QQualifierValue>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QQualifierValue>, scriptValueToQList<QQualifierValue>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QRaiseExceptionAction>, scriptValueToQSet<QRaiseExceptionAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QRaiseExceptionAction>, scriptValueToQList<QRaiseExceptionAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReadExtentAction>, scriptValueToQSet<QReadExtentAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReadExtentAction>, scriptValueToQList<QReadExtentAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReadIsClassifiedObjectAction>, scriptValueToQSet<QReadIsClassifiedObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReadIsClassifiedObjectAction>, scriptValueToQList<QReadIsClassifiedObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReadLinkAction>, scriptValueToQSet<QReadLinkAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReadLinkAction>, scriptValueToQList<QReadLinkAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReadLinkObjectEndAction>, scriptValueToQSet<QReadLinkObjectEndAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReadLinkObjectEndAction>, scriptValueToQList<QReadLinkObjectEndAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReadLinkObjectEndQualifierAction>, scriptValueToQSet<QReadLinkObjectEndQualifierAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReadLinkObjectEndQualifierAction>, scriptValueToQList<QReadLinkObjectEndQualifierAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReadSelfAction>, scriptValueToQSet<QReadSelfAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReadSelfAction>, scriptValueToQList<QReadSelfAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReadStructuralFeatureAction>, scriptValueToQSet<QReadStructuralFeatureAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReadStructuralFeatureAction>, scriptValueToQList<QReadStructuralFeatureAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReadVariableAction>, scriptValueToQSet<QReadVariableAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReadVariableAction>, scriptValueToQList<QReadVariableAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QRealization>, scriptValueToQSet<QRealization>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QRealization>, scriptValueToQList<QRealization>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReception>, scriptValueToQSet<QReception>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReception>, scriptValueToQList<QReception>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReclassifyObjectAction>, scriptValueToQSet<QReclassifyObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReclassifyObjectAction>, scriptValueToQList<QReclassifyObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QRedefinableElement>, scriptValueToQSet<QRedefinableElement>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QRedefinableElement>, scriptValueToQList<QRedefinableElement>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QRedefinableTemplateSignature>, scriptValueToQSet<QRedefinableTemplateSignature>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QRedefinableTemplateSignature>, scriptValueToQList<QRedefinableTemplateSignature>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReduceAction>, scriptValueToQSet<QReduceAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReduceAction>, scriptValueToQList<QReduceAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QRegion>, scriptValueToQSet<QRegion>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QRegion>, scriptValueToQList<QRegion>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QRelationship>, scriptValueToQSet<QRelationship>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QRelationship>, scriptValueToQList<QRelationship>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QRemoveStructuralFeatureValueAction>, scriptValueToQSet<QRemoveStructuralFeatureValueAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QRemoveStructuralFeatureValueAction>, scriptValueToQList<QRemoveStructuralFeatureValueAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QRemoveVariableValueAction>, scriptValueToQSet<QRemoveVariableValueAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QRemoveVariableValueAction>, scriptValueToQList<QRemoveVariableValueAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QReplyAction>, scriptValueToQSet<QReplyAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QReplyAction>, scriptValueToQList<QReplyAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QSendObjectAction>, scriptValueToQSet<QSendObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QSendObjectAction>, scriptValueToQList<QSendObjectAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QSendSignalAction>, scriptValueToQSet<QSendSignalAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QSendSignalAction>, scriptValueToQList<QSendSignalAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QSequenceNode>, scriptValueToQSet<QSequenceNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QSequenceNode>, scriptValueToQList<QSequenceNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QSignal>, scriptValueToQSet<QSignal>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QSignal>, scriptValueToQList<QSignal>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QSignalEvent>, scriptValueToQSet<QSignalEvent>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QSignalEvent>, scriptValueToQList<QSignalEvent>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QSlot>, scriptValueToQSet<QSlot>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QSlot>, scriptValueToQList<QSlot>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QStartClassifierBehaviorAction>, scriptValueToQSet<QStartClassifierBehaviorAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QStartClassifierBehaviorAction>, scriptValueToQList<QStartClassifierBehaviorAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QStartObjectBehaviorAction>, scriptValueToQSet<QStartObjectBehaviorAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QStartObjectBehaviorAction>, scriptValueToQList<QStartObjectBehaviorAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QState>, scriptValueToQSet<QState>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QState>, scriptValueToQList<QState>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QStateInvariant>, scriptValueToQSet<QStateInvariant>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QStateInvariant>, scriptValueToQList<QStateInvariant>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QStateMachine>, scriptValueToQSet<QStateMachine>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QStateMachine>, scriptValueToQList<QStateMachine>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QStereotype>, scriptValueToQSet<QStereotype>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QStereotype>, scriptValueToQList<QStereotype>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QStringExpression>, scriptValueToQSet<QStringExpression>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QStringExpression>, scriptValueToQList<QStringExpression>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QStructuralFeature>, scriptValueToQSet<QStructuralFeature>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QStructuralFeature>, scriptValueToQList<QStructuralFeature>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QStructuralFeatureAction>, scriptValueToQSet<QStructuralFeatureAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QStructuralFeatureAction>, scriptValueToQList<QStructuralFeatureAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QStructuredActivityNode>, scriptValueToQSet<QStructuredActivityNode>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QStructuredActivityNode>, scriptValueToQList<QStructuredActivityNode>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QStructuredClassifier>, scriptValueToQSet<QStructuredClassifier>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QStructuredClassifier>, scriptValueToQList<QStructuredClassifier>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QSubstitution>, scriptValueToQSet<QSubstitution>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QSubstitution>, scriptValueToQList<QSubstitution>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTemplateableElement>, scriptValueToQSet<QTemplateableElement>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTemplateableElement>, scriptValueToQList<QTemplateableElement>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTemplateBinding>, scriptValueToQSet<QTemplateBinding>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTemplateBinding>, scriptValueToQList<QTemplateBinding>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTemplateParameter>, scriptValueToQSet<QTemplateParameter>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTemplateParameter>, scriptValueToQList<QTemplateParameter>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTemplateParameterSubstitution>, scriptValueToQSet<QTemplateParameterSubstitution>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTemplateParameterSubstitution>, scriptValueToQList<QTemplateParameterSubstitution>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTemplateSignature>, scriptValueToQSet<QTemplateSignature>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTemplateSignature>, scriptValueToQList<QTemplateSignature>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTestIdentityAction>, scriptValueToQSet<QTestIdentityAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTestIdentityAction>, scriptValueToQList<QTestIdentityAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTimeConstraint>, scriptValueToQSet<QTimeConstraint>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTimeConstraint>, scriptValueToQList<QTimeConstraint>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTimeEvent>, scriptValueToQSet<QTimeEvent>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTimeEvent>, scriptValueToQList<QTimeEvent>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTimeExpression>, scriptValueToQSet<QTimeExpression>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTimeExpression>, scriptValueToQList<QTimeExpression>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTimeInterval>, scriptValueToQSet<QTimeInterval>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTimeInterval>, scriptValueToQList<QTimeInterval>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTimeObservation>, scriptValueToQSet<QTimeObservation>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTimeObservation>, scriptValueToQList<QTimeObservation>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTransition>, scriptValueToQSet<QTransition>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTransition>, scriptValueToQList<QTransition>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTrigger>, scriptValueToQSet<QTrigger>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTrigger>, scriptValueToQList<QTrigger>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QType>, scriptValueToQSet<QType>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QType>, scriptValueToQList<QType>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QTypedElement>, scriptValueToQSet<QTypedElement>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QTypedElement>, scriptValueToQList<QTypedElement>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QUnmarshallAction>, scriptValueToQSet<QUnmarshallAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QUnmarshallAction>, scriptValueToQList<QUnmarshallAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QUsage>, scriptValueToQSet<QUsage>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QUsage>, scriptValueToQList<QUsage>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QUseCase>, scriptValueToQSet<QUseCase>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QUseCase>, scriptValueToQList<QUseCase>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QValuePin>, scriptValueToQSet<QValuePin>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QValuePin>, scriptValueToQList<QValuePin>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QValueSpecification>, scriptValueToQSet<QValueSpecification>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QValueSpecification>, scriptValueToQList<QValueSpecification>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QValueSpecificationAction>, scriptValueToQSet<QValueSpecificationAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QValueSpecificationAction>, scriptValueToQList<QValueSpecificationAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QVariable>, scriptValueToQSet<QVariable>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QVariable>, scriptValueToQList<QVariable>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QVariableAction>, scriptValueToQSet<QVariableAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QVariableAction>, scriptValueToQList<QVariableAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QVertex>, scriptValueToQSet<QVertex>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QVertex>, scriptValueToQList<QVertex>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QWriteLinkAction>, scriptValueToQSet<QWriteLinkAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QWriteLinkAction>, scriptValueToQList<QWriteLinkAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QWriteStructuralFeatureAction>, scriptValueToQSet<QWriteStructuralFeatureAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QWriteStructuralFeatureAction>, scriptValueToQList<QWriteStructuralFeatureAction>);
        qScriptRegisterMetaType(scriptEngine, qSetToScriptValue<QWriteVariableAction>, scriptValueToQSet<QWriteVariableAction>);
        qScriptRegisterMetaType(scriptEngine, qListToScriptValue<QWriteVariableAction>, scriptValueToQList<QWriteVariableAction>);
    }
}

QT_END_NAMESPACE_QTUML

