######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 27 17:56:15 2012
######################################################################

TEMPLATE = app
TARGET = uml
DEPENDPATH += .
INCLUDEPATH += .

QT += uml

# Input
SOURCES += main.cpp
