isEmpty(DUSEMT_LIBRARY_BASENAME) {
    DUSEMT_LIBRARY_BASENAME = lib
}
DUSEMT_SOURCE_TREE = $$PWD
DUSEMT_LIBRARY_PATH = $$DUSEMT_SOURCE_TREE/$$DUSEMT_LIBRARY_BASENAME/duse-mt

LIBS += -L$$DUSEMT_LIBRARY_PATH

INCLUDEPATH += \
    $$DUSEMT_SOURCE_TREE/src/libs \
    $$DUSEMT_SOURCE_TREE/src/plugins

DUSEMT_APP_TARGET   = duse-mt
DUSEMT_APP_PATH = $$DUSEMT_SOURCE_TREE/bin
DUSEMT_PLUGIN_PATH  = $$DUSEMT_LIBRARY_PATH/plugins
